export const mockDonorData = {
  profile: {
    id: 'donor-001',
    name: 'Rajesh Kumar',
    bloodGroup: 'O+',
    lastDonation: '2024-06-15',
    eligibility: 'Eligible',
    availability: 'Available',
    location: 'Delhi, India',
    phone: '+91-98765-43210',
    email: 'rajesh@example.com',
  },
  notifications: [
    {
      id: 'notif-001',
      type: 'urgent',
      title: 'O+ Blood Needed',
      message: 'O+ blood is urgently required at City Hospital',
      distance: '3.1 km',
      hospital: 'City Hospital',
      timestamp: '2024-07-28T14:30:00Z',
    },
    {
      id: 'notif-002',
      type: 'normal',
      title: 'B+ Blood Required',
      message: 'B+ blood is needed at Apollo Hospital',
      distance: '5.2 km',
      hospital: 'Apollo Hospital',
      timestamp: '2024-07-27T10:15:00Z',
    },
  ],
  donationHistory: [
    {
      id: 'donation-001',
      date: '2024-06-15',
      location: 'City Blood Bank',
      units: 1,
      status: 'Completed',
    },
    {
      id: 'donation-002',
      date: '2024-03-10',
      location: 'Apollo Blood Bank',
      units: 1,
      status: 'Completed',
    },
    {
      id: 'donation-003',
      date: '2023-12-20',
      location: 'City Blood Bank',
      units: 1,
      status: 'Completed',
    },
  ],
  nearbyDonationCenters: [
    {
      id: 'center-001',
      name: 'City Blood Bank',
      address: '123 Main St, Delhi',
      distance: '1.2 km',
      hours: '9 AM - 6 PM',
    },
    {
      id: 'center-002',
      name: 'Apollo Blood Center',
      address: '456 Medical Ave, Delhi',
      distance: '2.8 km',
      hours: '8 AM - 8 PM',
    },
    {
      id: 'center-003',
      name: 'Red Cross Blood Bank',
      address: '789 Health Rd, Delhi',
      distance: '4.5 km',
      hours: '10 AM - 5 PM',
    },
  ],
}

export const mockHospitalData = {
  profile: {
    id: 'hospital-001',
    name: 'City Hospital',
    location: 'Delhi, India',
    bedCapacity: 500,
    contactPerson: 'Dr. Sharma',
    phone: '+91-11-2345-6789',
    email: 'admin@cityhospital.in',
  },
  inventory: [
    {
      id: 'inv-001',
      bloodGroup: 'O+',
      available: 45,
      reserved: 10,
      expiring: 5,
    },
    {
      id: 'inv-002',
      bloodGroup: 'O-',
      available: 12,
      reserved: 3,
      expiring: 2,
    },
    {
      id: 'inv-003',
      bloodGroup: 'A+',
      available: 38,
      reserved: 8,
      expiring: 3,
    },
    {
      id: 'inv-004',
      bloodGroup: 'B+',
      available: 52,
      reserved: 12,
      expiring: 6,
    },
  ],
  bloodRequests: [
    {
      id: 'req-001',
      bloodGroup: 'O+',
      units: 5,
      priority: 'Emergency',
      status: 'Pending',
      requestedAt: '2024-07-28T14:30:00Z',
    },
    {
      id: 'req-002',
      bloodGroup: 'A+',
      units: 3,
      priority: 'High',
      status: 'Fulfilled',
      requestedAt: '2024-07-28T12:00:00Z',
    },
    {
      id: 'req-003',
      bloodGroup: 'B+',
      units: 4,
      priority: 'Normal',
      status: 'Processing',
      requestedAt: '2024-07-28T10:15:00Z',
    },
  ],
  nearbyHospitals: [
    {
      id: 'hosp-001',
      name: 'Apollo Hospital',
      distance: '2.5 km',
      inventory: { 'O+': 30, 'O-': 8, 'A+': 25, 'B+': 40 },
    },
    {
      id: 'hosp-002',
      name: 'Max Healthcare',
      distance: '3.8 km',
      inventory: { 'O+': 50, 'O-': 15, 'A+': 35, 'B+': 45 },
    },
  ],
  nearbyBloodBanks: [
    {
      id: 'bb-001',
      name: 'City Blood Bank',
      distance: '1.2 km',
      inventory: { 'O+': 100, 'O-': 40, 'A+': 80, 'B+': 90 },
    },
  ],
}

export const mockBloodBankData = {
  profile: {
    id: 'bb-001',
    name: 'City Blood Bank',
    location: 'Delhi, India',
    capacity: 5000,
    contactPerson: 'Mr. Patel',
    phone: '+91-11-8765-4321',
    email: 'admin@citybloodbank.in',
  },
  inventory: [
    {
      id: 'inv-001',
      bloodGroup: 'O+',
      total: 280,
      available: 200,
      reserved: 50,
      expiringIn: 3,
    },
    {
      id: 'inv-002',
      bloodGroup: 'O-',
      total: 150,
      available: 90,
      reserved: 40,
      expiringIn: 5,
    },
    {
      id: 'inv-003',
      bloodGroup: 'A+',
      total: 220,
      available: 160,
      reserved: 45,
      expiringIn: 2,
    },
    {
      id: 'inv-004',
      bloodGroup: 'B+',
      total: 240,
      available: 180,
      reserved: 50,
      expiringIn: 4,
    },
  ],
  incomingDonations: [
    {
      id: 'donation-001',
      donorId: 'donor-123',
      bloodGroup: 'O+',
      units: 1,
      status: 'Scheduled',
      date: '2024-07-29',
      time: '10:00 AM',
    },
    {
      id: 'donation-002',
      donorId: 'donor-456',
      bloodGroup: 'A+',
      units: 1,
      status: 'Scheduled',
      date: '2024-07-29',
      time: '2:00 PM',
    },
  ],
  outgoingTransfers: [
    {
      id: 'transfer-001',
      hospitalId: 'hospital-001',
      hospitalName: 'City Hospital',
      bloodGroup: 'O+',
      units: 10,
      status: 'Dispatched',
      dispatchedAt: '2024-07-28T15:30:00Z',
      eta: '2024-07-28T16:15:00Z',
    },
    {
      id: 'transfer-002',
      hospitalId: 'hospital-002',
      hospitalName: 'Apollo Hospital',
      bloodGroup: 'A+',
      units: 5,
      status: 'Delivered',
      dispatchedAt: '2024-07-28T13:00:00Z',
      deliveredAt: '2024-07-28T13:45:00Z',
    },
  ],
  expiringBlood: [
    {
      id: 'exp-001',
      bloodGroup: 'O+',
      units: 8,
      expiringDate: '2024-07-31',
      daysLeft: 3,
    },
    {
      id: 'exp-002',
      bloodGroup: 'A+',
      units: 5,
      expiringDate: '2024-08-02',
      daysLeft: 5,
    },
  ],
}

export const mockAdminData = {
  systemStats: {
    totalHospitals: 42,
    totalBloodBanks: 18,
    totalDonors: 2850,
    totalInventory: 15420,
  },
  cityBloodAvailability: [
    { bloodGroup: 'O+', units: 3200, status: 'Sufficient' },
    { bloodGroup: 'O-', units: 420, status: 'Critical' },
    { bloodGroup: 'A+', units: 2800, status: 'Sufficient' },
    { bloodGroup: 'A-', units: 380, status: 'Low' },
    { bloodGroup: 'B+', units: 3100, status: 'Sufficient' },
    { bloodGroup: 'B-', units: 320, status: 'Low' },
    { bloodGroup: 'AB+', units: 1200, status: 'Sufficient' },
    { bloodGroup: 'AB-', units: 200, status: 'Critical' },
  ],
  hospitalsList: [
    {
      id: 'hospital-001',
      name: 'City Hospital',
      location: 'Delhi',
      bloodRequests: 12,
      status: 'Active',
      lastActivity: '2024-07-28T14:30:00Z',
    },
    {
      id: 'hospital-002',
      name: 'Apollo Hospital',
      location: 'Delhi',
      bloodRequests: 5,
      status: 'Active',
      lastActivity: '2024-07-28T13:00:00Z',
    },
    {
      id: 'hospital-003',
      name: 'Max Healthcare',
      location: 'Delhi',
      bloodRequests: 8,
      status: 'Active',
      lastActivity: '2024-07-28T12:15:00Z',
    },
  ],
  bloodBanksList: [
    {
      id: 'bb-001',
      name: 'City Blood Bank',
      location: 'Delhi',
      inventory: 5280,
      status: 'Active',
      lastActivity: '2024-07-28T14:00:00Z',
    },
    {
      id: 'bb-002',
      name: 'Red Cross Blood Bank',
      location: 'Delhi',
      inventory: 3420,
      status: 'Active',
      lastActivity: '2024-07-28T13:30:00Z',
    },
  ],
  emergencyRequests: [
    {
      id: 'emerg-001',
      hospital: 'City Hospital',
      bloodGroup: 'O-',
      units: 10,
      priority: 'Critical',
      status: 'In Progress',
      createdAt: '2024-07-28T14:30:00Z',
    },
    {
      id: 'emerg-002',
      hospital: 'Apollo Hospital',
      bloodGroup: 'A+',
      units: 5,
      priority: 'High',
      status: 'Fulfilled',
      createdAt: '2024-07-28T12:00:00Z',
    },
  ],
  recentNotifications: [
    {
      id: 'notif-001',
      type: 'alert',
      message: 'Critical shortage of O- blood detected',
      timestamp: '2024-07-28T15:00:00Z',
    },
    {
      id: 'notif-002',
      type: 'info',
      message: '500 units collected from blood donation drive',
      timestamp: '2024-07-28T12:30:00Z',
    },
  ],
}

export const mockAIPredictionData = {
  bloodShortagePrediction: [
    { bloodGroup: 'O-', currentUnits: 45, minRequired: 80, daysUntilShortage: 2, riskLevel: 'Critical' },
    { bloodGroup: 'A-', currentUnits: 120, minRequired: 100, daysUntilShortage: 5, riskLevel: 'Moderate' },
    { bloodGroup: 'B-', currentUnits: 85, minRequired: 90, daysUntilShortage: 7, riskLevel: 'Low' },
    { bloodGroup: 'AB-', currentUnits: 30, minRequired: 50, daysUntilShortage: 1, riskLevel: 'Critical' },
    { bloodGroup: 'O+', currentUnits: 220, minRequired: 150, daysUntilShortage: 10, riskLevel: 'Safe' },
  ],
  demandPrediction: [
    { date: 'Jul 29', O_positive: 45, O_negative: 12, A_positive: 38, A_negative: 8, B_positive: 52, B_negative: 10, AB_positive: 15, AB_negative: 3 },
    { date: 'Jul 30', O_positive: 52, O_negative: 15, A_positive: 42, A_negative: 10, B_positive: 58, B_negative: 12, AB_positive: 18, AB_negative: 4 },
    { date: 'Jul 31', O_positive: 48, O_negative: 13, A_positive: 40, A_negative: 9, B_positive: 55, B_negative: 11, AB_positive: 16, AB_negative: 3 },
    { date: 'Aug 1', O_positive: 58, O_negative: 18, A_positive: 46, A_negative: 12, B_positive: 62, B_negative: 14, AB_positive: 20, AB_negative: 5 },
    { date: 'Aug 2', O_positive: 55, O_negative: 16, A_positive: 44, A_negative: 11, B_positive: 60, B_negative: 13, AB_positive: 19, AB_negative: 4 },
    { date: 'Aug 3', O_positive: 62, O_negative: 19, A_positive: 50, A_negative: 13, B_positive: 68, B_negative: 15, AB_positive: 22, AB_negative: 5 },
    { date: 'Aug 4', O_positive: 60, O_negative: 17, A_positive: 48, A_negative: 12, B_positive: 65, B_negative: 14, AB_positive: 21, AB_negative: 5 },
  ],
  expiryPrediction: [
    { date: 'Jul 29', O_positive: 8, A_positive: 5, B_positive: 6, AB_positive: 2 },
    { date: 'Jul 31', O_positive: 12, A_positive: 8, B_positive: 9, AB_positive: 3 },
    { date: 'Aug 2', O_positive: 15, A_positive: 10, B_positive: 12, AB_positive: 4 },
    { date: 'Aug 4', O_positive: 18, A_positive: 12, B_positive: 14, AB_positive: 5 },
    { date: 'Aug 6', O_positive: 22, A_positive: 15, B_positive: 17, AB_positive: 6 },
  ],
  supplyVsDemand: [
    { bloodGroup: 'O+', supply: 280, demand: 150, balance: 130 },
    { bloodGroup: 'O-', supply: 90, demand: 85, balance: 5 },
    { bloodGroup: 'A+', supply: 220, demand: 120, balance: 100 },
    { bloodGroup: 'A-', supply: 75, demand: 70, balance: 5 },
    { bloodGroup: 'B+', supply: 240, demand: 140, balance: 100 },
    { bloodGroup: 'B-', supply: 85, demand: 80, balance: 5 },
    { bloodGroup: 'AB+', supply: 160, demand: 80, balance: 80 },
    { bloodGroup: 'AB-', supply: 50, demand: 45, balance: 5 },
  ],
}

export const mockEmergencyCoordinationData = {
  emergencyRequests: [
    {
      id: 'emerg-001',
      hospital: 'City Hospital',
      bloodGroup: 'O-',
      units: 10,
      priority: 'Critical',
      status: 'In Progress',
      createdAt: '2024-07-29T14:30:00Z',
      patientName: 'Rajesh Kumar',
      patientAge: 45,
      condition: 'Severe Trauma',
    },
    {
      id: 'emerg-002',
      hospital: 'Apollo Hospital',
      bloodGroup: 'A+',
      units: 5,
      priority: 'High',
      status: 'Pending',
      createdAt: '2024-07-29T13:45:00Z',
      patientName: 'Priya Sharma',
      patientAge: 32,
      condition: 'Post-Surgical',
    },
    {
      id: 'emerg-003',
      hospital: 'Max Healthcare',
      bloodGroup: 'B+',
      units: 8,
      priority: 'Critical',
      status: 'In Progress',
      createdAt: '2024-07-29T12:15:00Z',
      patientName: 'Vikram Singh',
      patientAge: 58,
      condition: 'Accident Victim',
    },
  ],
  recommendedHospitals: [
    {
      id: 'hosp-001',
      name: 'Apollo Hospital',
      distance: '2.5 km',
      bloodGroup: 'O-',
      available: 12,
      eta: '8 minutes',
      matchScore: 95,
    },
    {
      id: 'hosp-002',
      name: 'Max Healthcare',
      distance: '3.8 km',
      bloodGroup: 'O-',
      available: 8,
      eta: '12 minutes',
      matchScore: 88,
    },
    {
      id: 'hosp-003',
      name: 'Fortis Hospital',
      distance: '1.2 km',
      bloodGroup: 'O-',
      available: 6,
      eta: '5 minutes',
      matchScore: 92,
    },
  ],
  recommendedBloodBanks: [
    {
      id: 'bb-001',
      name: 'City Blood Bank',
      distance: '1.2 km',
      bloodGroup: 'O-',
      available: 20,
      transferTime: '15 minutes',
      matchScore: 98,
    },
    {
      id: 'bb-002',
      name: 'Red Cross Blood Center',
      distance: '2.5 km',
      bloodGroup: 'O-',
      available: 15,
      transferTime: '20 minutes',
      matchScore: 95,
    },
    {
      id: 'bb-003',
      name: 'Apollo Blood Bank',
      distance: '3.1 km',
      bloodGroup: 'O-',
      available: 10,
      transferTime: '25 minutes',
      matchScore: 85,
    },
  ],
  recommendedDonors: [
    {
      id: 'donor-001',
      name: 'Amit Patel',
      bloodGroup: 'O-',
      distance: '0.8 km',
      availability: 'Available Now',
      lastDonation: '2024-05-10',
      donationCount: 18,
      matchScore: 99,
      phone: '+91-9876543210',
    },
    {
      id: 'donor-002',
      name: 'Neha Gupta',
      bloodGroup: 'O-',
      distance: '1.5 km',
      availability: 'Available in 30 min',
      lastDonation: '2024-06-20',
      donationCount: 12,
      matchScore: 96,
      phone: '+91-9876543211',
    },
    {
      id: 'donor-003',
      name: 'Rohan Verma',
      bloodGroup: 'O-',
      distance: '2.3 km',
      availability: 'Available in 1 hour',
      lastDonation: '2024-07-15',
      donationCount: 25,
      matchScore: 94,
      phone: '+91-9876543212',
    },
  ],
}
